spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      webAllowOthers: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    platform: h2
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG